# Generated by Django 4.2.23 on 2025-08-12 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="branding_name",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="footer_text",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="subdomain",
        ),
        migrations.AddField(
            model_name="clinic",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="agreement_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinic",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="contact_role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="license_status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="sonsent_template",
            field=models.FileField(blank=True, null=True, upload_to="clinic_docs/"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="clinic_admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
