# Generated by Django 4.2.23 on 2025-08-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_remove_clinic_branding_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinic",
            old_name="contact_person",
            new_name="contact_person_name",
        ),
        migrations.RenameField(
            model_name="clinic",
            old_name="contact_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="clinic",
            old_name="contact_role",
            new_name="role",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="province",
        ),
    ]
