# Generated by Django 5.1.7 on 2025-08-19 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0003_rename_contact_person_clinic_contact_person_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="clinic_admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
