# Generated by Django 4.2.23 on 2025-08-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_remove_clinic_branding_name_and_more"),
        ("therapy", "0003_parentprofile_therapistprofile_child_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="specialization",
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="dbone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="assigned_therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="therapy.therapistprofile",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="therapy.parentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapists",
                to="clinic.clinic",
            ),
        ),
    ]
