# Generated by Django 4.2.23 on 2025-08-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0005_assignment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parentprofile",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="clinic",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="first_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="parent_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
