# Generated by Django 5.2.4 on 2025-08-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_rename_contact_person_clinic_contact_person_name_and_more"),
        ("therapy", "0006_rename_phone_parentprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentprofile",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
