# Generated by Django 5.2.4 on 2025-08-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0007_alter_parentprofile_options_parentprofile_clinic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentprofile",
            name="clinic",
        ),
    ]
