# Generated by Django 5.2.4 on 2025-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0008_remove_parentprofile_clinic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="therapistprofile",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Therapist",
                "verbose_name_plural": "Therapists",
            },
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="clinic",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="first_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="last_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
