# Generated by Django 5.1.7 on 2025-08-19 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("therapy", "0010_parentprofile_user_therapistprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="therapistprofile",
            old_name="dbone_number",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="phone",
        ),
    ]
