# Generated by Django 5.1.7 on 2025-08-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0005_rename_sonsent_template_clinic_consent_template"),
        ("therapy", "0011_rename_dbone_number_therapistprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="therapists",
                to="clinic.clinic",
            ),
        ),
    ]
